WebApp/WebApp/Models/Singer.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Models
{
    [JsonObject]
    public class Singer
    {
        [JsonProperty("singerid")]
        public int Singerid { get; set; }
        [JsonProperty("name")]
        public string Name { get; set; }
        [JsonProperty("biography")]
        public string Biography { get; set; }
        [JsonProperty("picture")]
        public string Picture { get; set; }
        [JsonProperty("bigPicture")]
        public string BigPicture { get; set; }
        [JsonProperty("countSongs")]
        public string CountSongs { get; set; }
        [JsonProperty("countViews")]
        public string CountViews { get; set; }
        [JsonProperty("linkToSinger")]
        public string LinkToSinger { get; set; }
        [JsonIgnore]
        public virtual ICollection<SuiteСhord> SuiteChords { get; set; }
        public Singer()
        {
            SuiteChords = new List<SuiteСhord>();
        }

        public Singer(string name, string picture, string countSongs, string countViews, string linkToSinger, string bigPicture, string biography)
        {
            this.Name = name;
            this.Picture = picture;
            this.CountSongs = countSongs;
            this.CountViews = countViews;
            this.LinkToSinger = linkToSinger;
            this.BigPicture = bigPicture;
            this.Biography = biography;
        }
    }
}

WebApp/WebApp/Controllers/SingerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;
using WebApp.Parser;
using PagedList.Mvc;
using PagedList;

namespace WebApp.Controllers
{
    public class SingerController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Singer(int? page, int id, string sortOrder)
        {
            //ViewBag.id = String.IsNullOrEmpty(sortOrder) ? "name_desc" : ""; 
            //ViewBag.CurrentSort = sortOrder;
            Singer singer = db.Singers.Find(id);
            ViewBag.page = (page ?? 1);
            //ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            //switch (sortOrder)
            //{
            //    case "name_desc":
            //        singer = singer.SuiteChords.OrderByDescending(s => s).ToList();
            //        break;
            //    default:
            //        singer = singer.OrderBy(s => s.Name).ToList();
            //        break;
            //}
            return View(singer);
        }

        public PartialViewResult ListSongs(int? page, int id)
        {
            Singer singer = db.Singers.Find(id);
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            ViewBag.page = pageNumber;
            return PartialView("SuiteChordList", singer.SuiteChords.OrderBy(s => s.SuiteСhordId).ToPagedList(pageNumber, pageSize));
        }
    }
}

WebApp/WebApp/Views/Singer/Singer.cshtml
@model WebApp.Models.Singer
@using PagedList.Mvc;
@using PagedList;
<h1>@Model.Name</h1>
<div class="positions_cont">
    <div class="left-cont">
        <p>@Model.CountSongs Suite Chords</p>
        @if (Model.Biography != null)
        {
            @Model.Biography;
        }
    </div>
    <div class="right-cont">
        @if (Model.BigPicture != null)
        {
            <img src="@Url.Content(@Model.BigPicture)" />
        }

    </div>
</div>
<div id="container">
    @{Html.RenderAction("ListSongs", "Singer", new { page = ViewBag.page, id = Model.Singerid });}
    @Html.PagedListPager(@Model.SuiteChords.ToPagedList((int)ViewBag.page, 10), page => Url.Action("Singer", new { page, sortOrder = ViewBag.CurrentSort }))
</div>